version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixcsoft
      MONGO_INITDB_ROOT_PASSWORD: ixcsoft
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db